### ISSUE TITLE
the code is Deprecated

### ISSUE THREAD

**Issue by wenyangchou** [jgrandja/spring-security-oauth-2-4-migrate#1]
![image](https://user-images.githubusercontent.com/28835129/69510024-1c164300-0f76-11ea-9aea-7196eb67bbec.png)

the latest version is deprecated?

**Comment by jgrandja** [comment]
@wenyangchou Please see latest [announcement](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update).
