### ISSUE TITLE
use deprecated class

### ISSUE THREAD

**Issue by cooperlyt** [jgrandja/spring-security-oauth-2-4-migrate#2]
spring-security-oauth-2-4-migrate/resource-server/src/main/java/org/springframework/security/oauth/samples/config/ResourceServerConfig.java 

ResourceServerConfigurerAdapter    is  deprecated

**Comment by jgrandja** [comment]
@cooper-lyt Yes I'm aware the class is deprecated. The purpose of this sample is to demonstrate how to migrate from Spring Security OAuth 2.4.x (deprecated) to Spring Security 5.x OAuth support.
